### ISSUE TITLE
As a player I want to play a “Extreme Hit” card in order to first choose a color and then select a player that has to press the launch twice button and skip their turn. 

### ISSUE THREAD

**Issue by maurohirt** [sopra-fs22-group-24/server#21]
- [x] A player can play the “Extreme Hit” card regardless of color, number and symbol.. 
- [x] The player can then select a color and a player
- [x] The selected player has to press the launch button twice (could also be done automatically)
- [x] The player that is in the turn order after the selected player starts their turn. They have to play a card according to the chosen color.

**Comment by flruee** [comment]
This was changed a bit.
Instead of player plays card -> server ask player which color -> player tells color -> server ask which victim -> player tells victim -> server executes, we decided to do it all in one request.
The playCard endpoint was therefore changed to accept a card (if wildcard or extreme hit set the color), a player (always ignored except if card is extreme hit) and a uno flag which should be false per default
